import Head from "next/head";
import * as d3 from "d3";
import { Inter } from "next/font/google";
import BackgroundArt from "@/components/Dashboard/BackgroundArt";
import NavigationBar from "@/components/Dashboard/NavigationBar/NavigationBar";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-screen">
        <BackgroundArt />
        <NavigationBar />

        <div className="absolute top-0 left-0 min-h-screen h-fit w-screen">
          <div className="h-screen w-screen">Content</div>
          <div className="h-screen w-screen">Content</div>
        </div>
      </div>
    </>
  );
}
